# URL configuration
url: 'https://mysrcs.github.io'
baseUrl: "/"

# Metadata
title: 'mysrcs'
author: '@mysrcs'

# Includes and Collections
include: ["_pages"]
# collections: 
# - foo
# - bar

# Text to HTML Parser and it's configuration 
markdown: kramdown
kramdown:
  gfm_quirks: [paragraph_end]

# Default values 
defaults:
  - scope:
      path: ""
      type: posts
    values:
      is_post: true
      layout: post
      permalink: /:title/
  - scope:
      path: ""
      type: pages
    values:
      is_post: false
      layout: page
      permalink: /:title/
  - scope:
      path: ""
      type: docs
    values:
      is_post: false
      layout: documentation
      permalink: /docs/:categories/:title/
