name: Delete old workflow runs
on:
  push:
    branches: ["master"]

jobs:
  del_runs:
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: read
    steps:
      - name: Delete all workflow runs
        uses: christosgalano/delete-gh-workflow-runs@v1.0.0
        with:
          owner: ${{ github.repository_owner }}
          repo: ${{ inputs.repository }}
          token: ${{ github.TOKEN }}
