name: Delete old workflow runs
on:
  push:
    branches: ["main"]

jobs:
  del_runs:
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: read
    steps:
      - name: Delete workflow runs
        uses: Rubber1Duck/delete-old-workflow-runs@v0.4.0
        with:
          repository: mysrcs/mysrcs.github.io   # replace this with your own repository
          older-than-seconds: 100             # remove all workflow runs older than 1 day ( default 86400 )
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  remove-job:
    runs-on: ubuntu-latest
    steps:
    - id: result 
      uses: MichaelMelena/list-artifacts@v1
    - uses: MichaelMelena/remove-artifacts@v1
      with:
        artifacts: ${{ steps.result.outputs.artifacts }}
